// generated by tools/build_manifest.mjs
window.MANIFEST_ALL = [
 "scenes/bridge.js",
 "scenes/build.js",
 "scenes/chants.js",
 "scenes/chorus1.js",
 "scenes/chorus1_brand.js",
 "scenes/chorus2.js",
 "scenes/final.js",
 "scenes/hook.js",
 "scenes/outro.js",
 "scenes/pre1.js",
 "scenes/pre2.js",
 "scenes/verse1.js",
 "scenes/verse2.js"
];
window.MANIFEST_V2 = [
 "scenes_v2/_shared.js",
 "scenes_v2/bridge.js",
 "scenes_v2/chorus1.js",
 "scenes_v2/final.js",
 "scenes_v2/intro.js",
 "scenes_v2/outro.js",
 "scenes_v2/prechorus.js",
 "scenes_v2/verse1.js",
 "scenes_v2/verse2.js",
 "scenes_v2/verse3.js"
];
window.MANIFEST = (new URLSearchParams(location.search).get('scenes') || '').split(',').filter(Boolean);
if (!window.MANIFEST.length) window.MANIFEST = new URLSearchParams(location.search).get('v') === '2' ? window.MANIFEST_V2 : window.MANIFEST_ALL;
