// generated by tools/build_manifest.mjs
window.MANIFEST_ALL = [];
window.MANIFEST = (new URLSearchParams(location.search).get('scenes') || '').split(',').filter(Boolean);
if (!window.MANIFEST.length) window.MANIFEST = window.MANIFEST_ALL;
