// writes engine/manifest.js listing every production scene file (engine/scenes/*.js except test_*)
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'engine');
const files = fs.readdirSync(path.join(root, 'scenes')).filter(f => f.endsWith('.js') && !f.startsWith('test_')).sort().map(f => 'scenes/' + f);
fs.writeFileSync(path.join(root, 'manifest.js'), `// generated by tools/build_manifest.mjs\nwindow.MANIFEST_ALL = ${JSON.stringify(files, null, 1)};\nwindow.MANIFEST = (new URLSearchParams(location.search).get('scenes') || '').split(',').filter(Boolean);\nif (!window.MANIFEST.length) window.MANIFEST = window.MANIFEST_ALL;\n`);
console.log(files.length, 'scenes');
