#!/usr/bin/env python3
"""Build audio/timeline.js (window.TIMELINE) for the engine from a composition melody.json
(grid time, 128 BPM). Optionally a take's analysis.json is used to report drift.

usage: make_timeline.py melody.json [--out audio/timeline.js] [--audio song.mp3]
Lines: consecutive syllables sharing the same (section, line text). Words: syllables joined
while a syllable ends with '-'. Display spellings (e.g. AHN-YOUNG -> 안녕) come from DISPLAY.
"""
import argparse, json, os, re

DISPLAY = {'AHN-YOUNG!': '안녕!', 'AHN-YOUNG': '안녕', '(AHN-YOUNG!)': '(안녕!)'}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('melody')
    ap.add_argument('--out', default=os.path.join(os.path.dirname(__file__), '..', 'audio', 'timeline.js'))
    ap.add_argument('--audio', default='../audio/song.mp3')
    a = ap.parse_args()
    m = json.load(open(a.melody))
    words, lines = [], []
    cur_word = None
    for v in m['vocal']:
        syl = v['syl']
        if cur_word is None:
            cur_word = {'w': '', 's': v['start'], 'e': v['end'], 'sec': v['section'], 'line': v['line'], 'syl': []}
        cur_word['w'] += syl.rstrip('-') if syl.endswith('-') and not syl.endswith('--') else syl
        cur_word['e'] = v['end']
        cur_word['syl'].append({'s': round(v['start'], 3), 'e': round(v['end'], 3), 'p': v['p'], 'x': syl})
        if not syl.endswith('-'):
            w = cur_word
            w['s'], w['e'] = round(w['s'], 3), round(w['e'], 3)
            clean = w['w']
            w['d'] = DISPLAY.get(clean, clean)
            words.append(w)
            cur_word = None
    # lines
    for i, w in enumerate(words):
        key = (w['sec'], w['line'])
        if not lines or (lines[-1]['sec'], lines[-1]['text']) != key or w['s'] - lines[-1]['e'] > 1.5:
            lines.append({'id': len(lines), 'sec': w['sec'], 'text': w['line'], 's': w['s'], 'e': w['e'], 'words': []})
        L = lines[-1]
        L['words'].append({k: w[k] for k in ('w', 'd', 's', 'e', 'syl')})
        L['e'] = w['e']
    for L in lines:
        L['display'] = ' '.join(x['d'] for x in L['words'])
    tl = {'bpm': m['bpm'], 'offset': 0, 'duration': 144.0, 'beats': None, 'barPhase': 0,
          'sections': [{'name': s['name'], 'start': round(s['start'], 3), 'end': round(s['end'], 3), 'energy': s['energy']} for s in m['sections']],
          'words': [{k: w[k] for k in ('w', 'd', 's', 'e')} for w in words], 'lines': lines, 'audio': a.audio,
          'source': os.path.abspath(a.melody)}
    with open(a.out, 'w') as f:
        f.write('// generated by tools/make_timeline.py from the composition timeline (grid time)\n')
        f.write('window.TIMELINE = ' + json.dumps(tl, ensure_ascii=False) + ';\n')
    print(f'{len(words)} words, {len(lines)} lines -> {a.out}')
    for L in lines:
        print(f"{L['s']:7.2f}-{L['e']:7.2f} [{L['sec']}] {L['display']}")


if __name__ == '__main__':
    main()
