#!/usr/bin/env python3
"""Build audio/timeline.js from a Mureka task JSON (lyrics_sections with word timestamps) + beat tracking.

usage: mureka_timeline.py TASK.json --index 0 --audio SONG.wav [--out audio/timeline.js] [--offset 0]
Times are in real song seconds (v2 is authored on the song's own clock, no grid).
Sections: Mureka section_type + our lyric tag names (matched in order from the lyrics sheet if given).
"""
import argparse, json, os, re
import numpy as np


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('task'); ap.add_argument('--index', type=int, default=0); ap.add_argument('--audio', required=True)
    ap.add_argument('--lyrics', help='lyrics sheet to name sections by our [tags]')
    ap.add_argument('--out', default=os.path.join(os.path.dirname(__file__), '..', 'audio', 'timeline.js'))
    ap.add_argument('--offset', type=float, default=0.0, help='seconds added to every timestamp (e.g. if audio was trimmed)')
    ap.add_argument('--duration', type=float)
    ap.add_argument('--src', default='../audio/song.mp3')
    a = ap.parse_args()
    q = json.load(open(a.task))
    m = [c for c in q['choices'] if c.get('index') == a.index]
    ch = m[0] if m else q['choices'][min(a.index, len(q['choices']) - 1)]
    tags = []
    if a.lyrics:
        tags = [m.group(1) for m in re.finditer(r'^\[([^\]]+)\]', open(a.lyrics).read(), re.M)]
    import librosa
    y, sr = librosa.load(a.audio, sr=22050, mono=True)
    tempo, beats = librosa.beat.beat_track(y=y, sr=sr, units='time', tightness=120)
    dur = a.duration or len(y) / sr
    o = a.offset
    sections, lines, words = [], [], []
    for si, s in enumerate(ch.get('lyrics_sections', [])):
        name = tags[si] if si < len(tags) else s['section_type']
        sections.append({'name': name, 'type': s['section_type'], 'start': round(s['start'] / 1000 + o, 3), 'end': round(s['end'] / 1000 + o, 3)})
        for L in s.get('lines', []):
            raw = [w for w in L.get('words', []) if w['text'].strip()]
            ws = []
            for k, w in enumerate(raw):  # Mureka word ends are near-onsets: extend each word to the next onset (max 0.9 s)
                s0 = w['start'] / 1000 + o
                nxt = raw[k + 1]['start'] / 1000 + o if k + 1 < len(raw) else s0 + 0.6
                ws.append({'w': w['text'].strip(), 'd': w['text'].strip(), 's': round(s0, 3), 'e': round(min(nxt, s0 + 0.9), 3)})
            lines.append({'id': len(lines), 'sec': name, 'text': L['text'], 'display': L['text'], 's': ws[0]['s'] if ws else round(L['start'] / 1000 + o, 3), 'e': ws[-1]['e'] if ws else round(L['end'] / 1000 + o, 3), 'words': ws})
            words += ws
    tl = {'bpm': float(np.atleast_1d(tempo)[0]), 'offset': 0, 'duration': round(dur, 3), 'beats': [round(float(b), 4) for b in beats], 'barPhase': 0,
          'sections': sections, 'words': words, 'lines': lines, 'audio': a.src, 'source': {'task': q.get('id'), 'index': a.index, 'model': q.get('model')}}
    with open(a.out, 'w') as f:
        f.write('// generated by tools/mureka_timeline.py (real song time; Mureka word timestamps + librosa beats)\n')
        f.write('window.TIMELINE = ' + json.dumps(tl, ensure_ascii=False) + ';\n')
    print(f"bpm {tl['bpm']:.1f}, {len(beats)} beats, {len(sections)} sections, {len(lines)} lines, {len(words)} words, {dur:.1f}s")
    for s in sections:
        print(f"  {s['start']:7.2f}-{s['end']:7.2f}  {s['name']}")


if __name__ == '__main__':
    main()
